export type VietnamProvince = {
  id: number;
  countryId: number;
  name: string;
};

export const VIETNAM_PROVINCES: VietnamProvince[] = [
  { id: 17, countryId: 192, name: "Hà Nội" },
  { id: 18, countryId: 192, name: "Hà Giang" },
  { id: 19, countryId: 192, name: "Cao Bằng" },
  { id: 20, countryId: 192, name: "Bắc Kạn" },
  { id: 21, countryId: 192, name: "Tuyên Quang" },
  { id: 22, countryId: 192, name: "Lào Cai" },
  { id: 23, countryId: 192, name: "Điện Biên" },
  { id: 24, countryId: 192, name: "Lai Châu" },
  { id: 25, countryId: 192, name: "Sơn La" },
  { id: 26, countryId: 192, name: "Yên Bái" },
  { id: 27, countryId: 192, name: "Hoà Bình" },
  { id: 28, countryId: 192, name: "Thái Nguyên" },
  { id: 29, countryId: 192, name: "Lạng Sơn" },
  { id: 30, countryId: 192, name: "Quảng Ninh" },
  { id: 31, countryId: 192, name: "Bắc Giang" },
  { id: 32, countryId: 192, name: "Phú Thọ" },
  { id: 33, countryId: 192, name: "Vĩnh Phúc" },
  { id: 34, countryId: 192, name: "Bắc Ninh" },
  { id: 35, countryId: 192, name: "Hải Dương" },
  { id: 36, countryId: 192, name: "Hải Phòng" },
  { id: 37, countryId: 192, name: "Hưng Yên" },
  { id: 38, countryId: 192, name: "Thái Bình" },
  { id: 39, countryId: 192, name: "Hà Nam" },
  { id: 40, countryId: 192, name: "Nam Định" },
  { id: 41, countryId: 192, name: "Ninh Bình" },
  { id: 42, countryId: 192, name: "Thanh Hóa" },
  { id: 43, countryId: 192, name: "Nghệ An" },
  { id: 44, countryId: 192, name: "Hà Tĩnh" },
  { id: 45, countryId: 192, name: "Quảng Bình" },
  { id: 46, countryId: 192, name: "Quảng Trị" },
  { id: 47, countryId: 192, name: "Huế" },
  { id: 48, countryId: 192, name: "Đà Nẵng" },
  { id: 49, countryId: 192, name: "Quảng Nam" },
  { id: 50, countryId: 192, name: "Quảng Ngãi" },
  { id: 51, countryId: 192, name: "Bình Định" },
  { id: 52, countryId: 192, name: "Phú Yên" },
  { id: 53, countryId: 192, name: "Khánh Hòa" },
  { id: 54, countryId: 192, name: "Ninh Thuận" },
  { id: 55, countryId: 192, name: "Bình Thuận" },
  { id: 56, countryId: 192, name: "Kon Tum" },
  { id: 57, countryId: 192, name: "Gia Lai" },
  { id: 58, countryId: 192, name: "Đắk Lắk" },
  { id: 59, countryId: 192, name: "Đắk Nông" },
  { id: 60, countryId: 192, name: "Lâm Đồng" },
  { id: 61, countryId: 192, name: "Bình Phước" },
  { id: 62, countryId: 192, name: "Tây Ninh" },
  { id: 63, countryId: 192, name: "Bình Dương" },
  { id: 64, countryId: 192, name: "Đồng Nai" },
  { id: 65, countryId: 192, name: "Bà Rịa - Vũng Tàu" },
  { id: 66, countryId: 192, name: "Hồ Chí Minh" },
  { id: 67, countryId: 192, name: "Long An" },
  { id: 68, countryId: 192, name: "Tiền Giang" },
  { id: 69, countryId: 192, name: "Bến Tre" },
  { id: 70, countryId: 192, name: "Trà Vinh" },
  { id: 71, countryId: 192, name: "Vĩnh Long" },
  { id: 72, countryId: 192, name: "Đồng Tháp" },
  { id: 73, countryId: 192, name: "An Giang" },
  { id: 74, countryId: 192, name: "Kiên Giang" },
  { id: 75, countryId: 192, name: "Cần Thơ" },
  { id: 76, countryId: 192, name: "Hậu Giang" },
  { id: 77, countryId: 192, name: "Sóc Trăng" },
  { id: 78, countryId: 192, name: "Bạc Liêu" },
  { id: 79, countryId: 192, name: "Cà Mau" },
];
