import type { TryOnGlasses } from "./types";

export const glassesItems: TryOnGlasses[] = [
  {
    id: "round-silver-optical",
    name: "Round Silver Optical",
    imageUrl: "/tryon/glasses/ready/round-silver-optical.png",
    imageWidth: 1000,
    imageHeight: 401,
    leftLens: { x: 335, y: 198 },
    rightLens: { x: 668, y: 198 },
    scale: 0.94,
    offsetX: 0,
    offsetY: 0,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "square-clear-sunglasses",
    name: "Square Clear Sunglasses",
    imageUrl: "/tryon/glasses/ready/square-clear-sunglasses.png",
    imageWidth: 1000,
    imageHeight: 400,
    leftLens: { x: 330, y: 203 },
    rightLens: { x: 670, y: 203 },
    scale: 0.88,
    offsetX: 0,
    offsetY: 4,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "wrap-silver-sunglasses",
    name: "Wrap Silver Sunglasses",
    imageUrl: "/tryon/glasses/ready/wrap-silver-sunglasses.png",
    imageWidth: 1000,
    imageHeight: 400,
    leftLens: { x: 345, y: 198 },
    rightLens: { x: 647, y: 198 },
    scale: 0.85,
    offsetX: 0,
    offsetY: 0,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "wrap-black-sunglasses",
    name: "Wrap Black Sunglasses",
    imageUrl: "/tryon/glasses/ready/wrap-black-sunglasses.png",
    imageWidth: 1000,
    imageHeight: 400,
    leftLens: { x: 337, y: 214 },
    rightLens: { x: 665, y: 214 },
    scale: 0.92,
    offsetX: 0,
    offsetY: 0,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "teal-optical-frame",
    name: "Teal Optical Frame",
    imageUrl: "/tryon/glasses/ready/teal-optical-frame.png",
    imageWidth: 1000,
    imageHeight: 400,
    leftLens: { x: 300, y: 190 },
    rightLens: { x: 700, y: 190 },
    scale: 0.98,
    offsetX: 0,
    offsetY: 4,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "blue-square-sunglasses",
    name: "Blue Square Sunglasses",
    imageUrl: "/tryon/glasses/image_07.png",
    imageWidth: 1000,
    imageHeight: 400,
    leftLens: { x: 310, y: 200 },
    rightLens: { x: 695, y: 200 },
    scale: 0.9,
    offsetX: 0,
    offsetY: 6,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "gray-round-optical",
    name: "Gray Round Optical",
    imageUrl: "/tryon/glasses/image_08.png",
    imageWidth: 1000,
    imageHeight: 400,
    leftLens: { x: 252, y: 190 },
    rightLens: { x: 722, y: 190 },
    scale: 0.98,
    offsetX: 0,
    offsetY: 0,
    rotationOffset: 0,
    enabled: true,
  },
  {
    id: "rimless-gradient-sunglasses",
    name: "Rimless Gradient Sunglasses",
    imageUrl: "/tryon/glasses/ready/rimless-gradient-sunglasses.png",
    imageWidth: 1000,
    imageHeight: 401,
    leftLens: { x: 269, y: 206 },
    rightLens: { x: 735, y: 206 },
    scale: 1.02,
    offsetX: 0,
    offsetY: 5,
    rotationOffset: 0,
    enabled: true,
  },
];

export const enabledGlassesItems = glassesItems.filter(
  (glasses) => glasses.enabled === true,
);
